---
- name: ensure X11 config directory exists
  file:
    path: /etc/X11/xorg.conf.d
    mode: "0755"
    state: directory
    owner: root
    group: root

# Make sure we're running on a X1 Carbon 3rd gen
- debug: check for Lenovo Thinkpad hardware type
  failed_when: ansible_product_version != "ThinkPad X1 Carbon 3rd"

