---
# Make sure we're running on a X1 Carbon 3rd gen
- name: Check that current system is a Lenovo ThinkPad.
  fail:
    msg: >-
      Target system appears not to be a ThinkPad (found hardware type
      {{ ansible_product_version }}).
  when: "'ThinkPad' not in ansible_product_version"

- name: Set Thinkpad-compatible ACPI settings for power management.
  become: yes
  copy:
    src: thinkpad_acpi.conf
    dest: /etc/modprobe.d/
    owner: root
    group: root
    mode: "0644"
  when: thinkpad_configure_acpi == true
  notify:
    - update initramfs

# set up touchpad for more stable response
# This was necessary on ThinkPad X1 Carbon Third Gen for a while.
- name: Set IMPS options for touchpad performance.
  become: yes
  copy:
    src: psmouse.conf
    dest: /etc/modprobe.d/
    owner: root
    group: root
    mode: "0644"
  when: thinkpad_configure_imps == true
  notify:
    - update initramfs

- name: Create X11 config directory.
  become: yes
  file:
    path: /etc/X11/xorg.conf.d
    mode: "0755"
    state: directory
    owner: root
    group: root

- name: Set scroll-via-TrackPoint options in X11 config.
  become: yes
  copy:
    src: 11-evdev-trackpoint.conf
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
    mode: "0644"
  when: thinkpad_x11_trackpoint_scroll == true

# configure backlight settings so buttons work
- name: Add Intel backlight settings to X11 config.
  become: yes
  copy:
    src: 80-backlight.conf
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
    mode: "0644"
  when: thinkpad_intel_backlight == true
  tags: backlight
