---
- include: init.yml
- include: backlight.yml
- include: video.yml
- include: touchpad.yml

- name: add thinkpad acpi settings for power config
  copy:
    src: thinkpad_acpi.conf
    dest: /etc/modprobe.d/
    owner: root
    group: root
    mode: "0644"
  notify:
    - update initramfs
  tags:
    - thinkpad

- name: get custom xrandr screen resolution facts
  action: xrandr
  tags:
    - thinkpad

- name: display screen resolution
  debug: var=resolution_as_string
  tags:
    - thinkpad

