---
- name: Create X11 config directory.
  file:
    path: /etc/X11/xorg.conf.d
    mode: "0755"
    state: directory
    owner: root
    group: root

# Make sure we're running on a X1 Carbon 3rd gen
- debug: check for Lenovo Thinkpad hardware type
  failed_when: ansible_product_version != "ThinkPad X1 Carbon 3rd"

- name: Set Thinkpad-compatible ACPI settings for power management.
  copy:
    src: thinkpad_acpi.conf
    dest: /etc/modprobe.d/
    owner: root
    group: root
    mode: "0644"
  notify:
    - update initramfs
  tags:
    - thinkpad

# set up touchpad for more stable response
# This was necessary on ThinkPad X1 Carbon Third Gen for a while.
- name: Set IMPS options for touchpad performance.
  copy:
    src: psmouse.conf
    dest: /etc/modprobe.d/
    owner: root
    group: root
    mode: "0644"
  notify:
    - update initramfs

- name: Set scroll-via-TrackPoint options in X11 config.
  copy:
    src: 11-evdev-trackpoint.conf
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
    mode: "0644"
