---
# set up touchpad for more stable response
- name: add imps setting for touchpad config
  copy:
    src: psmouse.conf
    dest: /etc/modprobe.d/
    owner: root
    group: root
    mode: "0644"
  notify:
    - update initramfs
  tags:
    - thinkpad

- name: add touchpad settings to X11 config
  copy:
    src: 11-evdev-trackpoint.conf
    dest: /etc/modprobe.d/
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
    mode: "0644"
