---
# Fixes for distorted video on X1 Carbon 3rd Gen
# by way of bleeding edge video drivers. Vastly improves
# support for graphics hardware such as i915, which
# X1 Carbon uses.
- name: add graphics-drivers ppa
  apt_repository:
     repo: ppa:oibaf/graphics-drivers
     # Testing didn't show great results, so removing
     # the PPA to isolate changes elsewhere.
     state: absent

- name: disable ips screen in grub
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"'
    # Many resources recommend adding flags to improve performance
    # of the Intel 915. None confirmed working yet.
    # line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i915.enable_ips=0"'
  notify:
    - update grub

- name: downgrade X11 driver
  copy:
    src: 20-intel.conf
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
    mode: "0644"
  when: thinkpad_driver_downgrade is defined and thinkpad_driver_downgrade
  tags:
    - thinkpad

- name: remove driver downgrade if necessary
  file:
    path: /etc/X11/xorg.conf.d/20-intel.conf
    state: absent
  when: thinkpad_driver_downgrade is defined and not thinkpad_driver_downgrade

- name: add ubuntu proposed repo
  copy:
    src: ubuntu_proposed.list
    dest: /etc/apt/sources.list.d/
    mode: "0644"
    owner: root
    group: root

- name: add ubuntu proposed apt preferences
  copy:
    src: ubuntu_proposed.pref
    dest: /etc/apt/preferences.d/
    mode: "0644"
    owner: root
    group: root

- name: install proposed intel video driver package
  apt:
    name: xserver-xorg-video-intel-lts-utopic
    # Due to dependency hell, this package doesn't install cleanly,
    # so disabling for now.
    state: absent
