---
# fixes for distorted video on X1 Carbon 3rd Gen.
- name: add graphics-drivers ppa
  apt_repository:
     repo: ppa:oibaf/graphics-drivers
     state: present

- name: downgrade X11 driver
  copy:
    src: 20-intel.conf
    dest: /etc/modprobe.d/
    dest: /usr/share/X11/xorg.conf.d/
    owner: root
    group: root
    mode: "0644"
  when: thinkpad_driver_downgrade is defined and thinkpad_driver_downgrade
  tags:
    - thinkpad

- name: remove driver downgrade if necessary
  file:
    path: /etc/modprobe.d/20-intel.conf
    state: absent
  when: thinkpad_driver_downgrade is defined and not thinkpad_driver_downgrade

