---
# Fixes for distorted video on X1 Carbon 3rd Gen
# by way of bleeding edge video drivers. Vastly improves
# support for graphics hardware such as i915, which
# X1 Carbon uses.
- name: add graphics-drivers ppa
  apt_repository:
     repo: ppa:oibaf/graphics-drivers
     # Testing didn't show great results, so removing
     # the PPA to isolate changes elsewhere.
     state: absent

- name: disable ips screen in grub
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
#    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i915.enable_ips=0"'
  notify:
    - update grub

- name: downgrade X11 driver
  copy:
    src: 20-intel.conf
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
    mode: "0644"
  when: thinkpad_driver_downgrade is defined and thinkpad_driver_downgrade
  tags:
    - thinkpad

- name: remove driver downgrade if necessary
  file:
    path: /etc/modprobe.d/20-intel.conf
    state: absent
  when: thinkpad_driver_downgrade is defined and not thinkpad_driver_downgrade

